### ISSUE TITLE
[1주차] 예산 페이지 컴포넌트 개발

### ISSUE THREAD

**Issue by seong-dodo** [CodeSoom/project-react-4-seong-dodo#5]
##### 4주 프로젝트 (2021.6/28~2021.7/25)
# 🐜 Mine 애플리케이션
#### 1주차 핵심기능
우선순위 2. 사용자는 한 달 예산을 입력할 수 있다.

- [ ] 예산 입력 input 기능 개발한다.
- [ ] 예산 입력 컴포넌트 개발한다.
- [ ] 예산 입력 데이터 스키마를 정의한다.

**Comment by moonkii** [comment]
입력과 보여주는건 다른 기능으로 분리해서 하는건가요?

**Comment by seong-dodo** [comment]
안녕하세요. 
https://github.com/CodeSoom/project-react-4-seong-dodo/issues/5#issuecomment-872281027
제가 조금더 세부적으로 적었어야하는데.. 예산 입력 input에 입력을 하면 입력값이 바로 보여지도록 하였습니다. 😆😆😆 

다른 기능으로 분리는 추후 작업하면서 분리해야할지 고민해야 할 것 같습니다. 🤔🤔🤔

입력된 값은 우선 리덕스에 저장되는 방식으로 진행하였습니다. 서버에 저장해서 데이터를 저장하면 좋은데 그 부분은 추후 고민해봐야 할 것 같습니다. 그래서 우선은 `Google Firebase(https://firebase.google.com/?hl=ko)를 이용하여 백엔드를 직접 구현하지 않고 백엔드 기능을 사용합니다`를 사용해보려고 합니다!

**Comment by moonkii** [comment]
> 더 쪼개서 완성 된 모습이 아니더라도 PR을 올리는 방식으로 더 작게 나눠야 할까요?? 🤔🤔🤔

작업을 작게 쪼개는 건 좋은 습관이에요. 다만 하나의 PR 을 보낼 때 완성된 형태를 보내는게 중요해요.
여기서 완성된 형태란 내가 최종적으로 생각하는 형태의 모습이 아닌 최소한 기능적으로 사용할 수 있는 완성된 형태를 의미해요.
하나의 PR 자체가 기능 릴리즈에 가깝다고 생각하시면 돼요. 

아마 input 의 number 를 타입으로 잡으실 때 프로젝트에서 화살표를 사용하는 경우가 없을거에요.
이런 경우 글로벌 css 로 잡아주시면 좋아요. (이모션으로 잡아주더라도 큰 차이는 없어요)

```css
input[type=number]::-webkit-inner-spin-button,
input[type=number]::-webkit-outer-spin-button {
    -webkit-appearance: none;
    margin: 0;
}
```
